name: Build and Deploy .NET Application

on:
  push:
    branches:
      - main  # Ejecutar solo cuando se suben cambios a main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TuApp.sln

      - name: Build the app
        run: dotnet build TuApp.sln --configuration Release

      - name: Publish the app
        run: dotnet publish src/TuApp.Api/TuApp.Api.csproj --configuration Release --output ./publish


